services:
  - type: web
    name: someliar
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: GEMINI_API_KEY
        sync: false
      - key: CLOUDINARY_URL
        sync: false
    autoDeploy: true
