# Generated by Django 5.2.13 on 2026-04-18 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anotacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('prioridad', models.CharField(choices=[('urgente', 'Urgente'), ('moderado', 'Moderado'), ('normal', 'Normal')], default='normal', max_length=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('resuelta', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['resuelta', '-fecha'],
            },
        ),
    ]
