# Generated by Django 5.2.13 on 2026-04-13 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bodega', '0001_initial'),
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('pendiente', 'Pendiente de revisión'), ('enviado', 'Enviado'), ('recibido', 'Recibido')], default='borrador', max_length=20)),
                ('generado_por_ia', models.BooleanField(default=False)),
                ('texto_ia', models.TextField(blank=True, verbose_name='texto generado por IA')),
                ('notas', models.TextField(blank=True)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='proveedores.proveedor')),
            ],
            options={
                'verbose_name': 'pedido',
                'verbose_name_plural': 'pedidos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='LineaPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_sugerida', models.PositiveIntegerField()),
                ('cantidad_final', models.PositiveIntegerField(blank=True, null=True)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=8)),
                ('vino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas_pedido', to='bodega.vino')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='pedidos.pedido')),
            ],
            options={
                'verbose_name': 'línea de pedido',
                'verbose_name_plural': 'líneas de pedido',
            },
        ),
    ]
