# Generated by Django 5.2.13 on 2026-04-18 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('pendiente', 'Pendiente de revisión'), ('enviado', 'Enviado'), ('recibido', 'Recibido')], db_index=True, default='borrador', max_length=20),
        ),
    ]
