# Generated by Django 5.2.13 on 2026-04-13 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('anada', models.PositiveIntegerField(blank=True, null=True, verbose_name='añada')),
                ('familia', models.CharField(choices=[('blanco', 'Blanco'), ('tinto', 'Tinto'), ('rosado', 'Rosado'), ('espumoso', 'Espumoso'), ('generoso', 'Generoso'), ('dulce', 'Dulce')], max_length=20)),
                ('denominacion_origen', models.CharField(blank=True, max_length=200, verbose_name='denominación de origen')),
                ('precio_coste', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('precio_carta', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('notas', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'vino',
                'verbose_name_plural': 'vinos',
                'ordering': ['familia', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='StockConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_minimo', models.PositiveIntegerField(default=6)),
                ('stock_optimo', models.PositiveIntegerField(default=12)),
                ('vino', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock_config', to='bodega.vino')),
            ],
            options={
                'verbose_name': 'configuración de stock',
                'verbose_name_plural': 'configuraciones de stock',
            },
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida'), ('ajuste', 'Ajuste')], max_length=10)),
                ('cantidad', models.IntegerField(help_text='Positivo para entradas, negativo para salidas.')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('notas', models.TextField(blank=True)),
                ('vino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='bodega.vino')),
            ],
            options={
                'verbose_name': 'movimiento',
                'verbose_name_plural': 'movimientos',
                'ordering': ['-fecha'],
            },
        ),
    ]
