# Generated by Django 5.2.13 on 2026-04-13 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vino',
            name='azucar',
            field=models.CharField(blank=True, help_text='Ej: Brut, Brut Nature, Extra Brut, Rosado...', max_length=100, verbose_name='tipo/azúcar'),
        ),
        migrations.AddField(
            model_name='vino',
            name='bodega_nombre',
            field=models.CharField(blank=True, max_length=200, verbose_name='bodega'),
        ),
        migrations.AddField(
            model_name='vino',
            name='en_canitas',
            field=models.BooleanField(default=False, verbose_name='Cañitas'),
        ),
        migrations.AddField(
            model_name='vino',
            name='en_ene',
            field=models.BooleanField(default=False, verbose_name='EÑE'),
        ),
        migrations.AddField(
            model_name='vino',
            name='en_pool',
            field=models.BooleanField(default=False, verbose_name='Pool'),
        ),
        migrations.AddField(
            model_name='vino',
            name='variedades',
            field=models.CharField(blank=True, max_length=300, verbose_name='variedades de uva'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='cantidad',
            field=models.DecimalField(decimal_places=1, help_text='Positivo para entradas, negativo para salidas.', max_digits=8),
        ),
        migrations.AlterField(
            model_name='vino',
            name='familia',
            field=models.CharField(choices=[('espumoso_nac', 'Burbujas Nacional'), ('champagne', 'Champagne'), ('espumoso_int', 'Burbujas Internacional (Otros)'), ('blanco_nac', 'Blanco Nacional'), ('blanco_int', 'Blanco Internacional'), ('tinto_nac', 'Tinto Nacional'), ('tinto_int', 'Tinto Internacional'), ('grandes_tintos', 'Grandes Vinos Tintos'), ('rosado', 'Rosado'), ('dulce', 'Dulce'), ('generoso', 'Generoso'), ('fuera_carta', 'Fuera de Carta'), ('propiedad', 'Vinos de Propiedad')], max_length=20),
        ),
    ]
