# Generated by Django 5.2.13 on 2026-04-13 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0002_vino_azucar_vino_bodega_nombre_vino_en_canitas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vino',
            name='es_copa',
            field=models.BooleanField(default=False, verbose_name='se vende por copas'),
        ),
        migrations.AddField(
            model_name='vino',
            name='precio_copa',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='precio copa en carta'),
        ),
        migrations.AddField(
            model_name='vino',
            name='via_coupa',
            field=models.BooleanField(default=False, help_text='Si True, se pide por el sistema corporativo Meliá.', verbose_name='se pide por Coupa'),
        ),
    ]
