# Generated by Django 5.2.13 on 2026-04-18 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0003_vino_es_copa_vino_precio_copa_vino_via_coupa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vino',
            name='activo',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
