# Generated by Django 5.2.13 on 2026-04-20 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0004_add_indexes_activo_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('color', models.CharField(choices=[('primary', 'Azul'), ('success', 'Verde'), ('danger', 'Rojo'), ('warning', 'Amarillo'), ('info', 'Cian'), ('secondary', 'Gris'), ('dark', 'Negro')], default='secondary', max_length=20)),
            ],
            options={
                'verbose_name': 'etiqueta',
                'verbose_name_plural': 'etiquetas',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='vino',
            name='etiquetas',
            field=models.ManyToManyField(blank=True, related_name='vinos', to='bodega.etiqueta', verbose_name='etiquetas'),
        ),
    ]
