# Generated by Django 5.2.13 on 2026-04-20 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0005_etiqueta_vino_etiquetas'),
    ]

    operations = [
        migrations.AddField(
            model_name='vino',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Foto de la etiqueta o botella.', upload_to='vinos/'),
        ),
    ]
