# Generated by Django 5.2.13 on 2026-04-20 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0006_vino_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='vino',
            name='descripcion_ia',
            field=models.TextField(blank=True),
        ),
    ]
