# Generated by Django 5.2.13 on 2026-04-13 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bodega', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('contacto', models.CharField(blank=True, max_length=200, verbose_name='persona de contacto')),
                ('notas', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'proveedor',
                'verbose_name_plural': 'proveedores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='VinoProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(blank=True, max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('es_principal', models.BooleanField(default=False)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinos', to='proveedores.proveedor')),
                ('vino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vino_proveedores', to='bodega.vino')),
            ],
            options={
                'verbose_name': 'vino-proveedor',
                'verbose_name_plural': 'vinos-proveedores',
                'unique_together': {('vino', 'proveedor')},
            },
        ),
    ]
